param(
    [string]$Branch = "main",
    [string]$Remote = "origin",
    [string]$DeployHost = $(if ($env:EXCELCC_DEPLOY_HOST) { $env:EXCELCC_DEPLOY_HOST } else { "38.76.169.222" }),
    [int]$DeployPort = $(if ($env:EXCELCC_DEPLOY_PORT) { [int]$env:EXCELCC_DEPLOY_PORT } else { 22 }),
    [string]$DeployUser = $(if ($env:EXCELCC_DEPLOY_USER) { $env:EXCELCC_DEPLOY_USER } else { "root" }),
    [string]$DeployRepoDir = $(if ($env:EXCELCC_DEPLOY_REPO_DIR) { $env:EXCELCC_DEPLOY_REPO_DIR } else { "/www/wwwroot/excelcc/kick-deploy/repo" }),
    [string]$ChangeScope = "ExcelCC production update",
    [switch]$SkipQualityGate,
    [switch]$SkipOnlineLog
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$Root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$PublicChecks = @(
    "https://www.excelcc.cn/",
    "https://www.excelcc.cn/api/public/home-overview",
    "https://www.excelcc.cn/practice",
    "https://www.excelcc.cn/api/practice/campaign/chapters"
)

function Invoke-Step {
    param(
        [string]$Name,
        [scriptblock]$Action
    )
    Write-Host ""
    Write-Host "==> $Name"
    & $Action
}

function Invoke-Native {
    param(
        [string]$FilePath,
        [string[]]$Arguments
    )
    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed: $FilePath $($Arguments -join ' ')"
    }
}

function Get-GitOutput {
    param([string[]]$Arguments)
    $output = & git @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "git $($Arguments -join ' ') failed"
    }
    return ($output -join "`n").Trim()
}

function Get-PlainPassword {
    if ($env:EXCELCC_DEPLOY_PASSWORD) {
        return $env:EXCELCC_DEPLOY_PASSWORD
    }
    $secure = Read-Host "EXCELCC_DEPLOY_PASSWORD" -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Invoke-RemoteDeploy {
    param([switch]$SyncOnly)
    $args = @(
        "scripts/deploy/remote_deploy.py",
        "--host", $DeployHost,
        "--port", "$DeployPort",
        "--user", $DeployUser,
        "--repo-dir", $DeployRepoDir,
        "--branch", $Branch
    )
    if ($SyncOnly) {
        $args += "--sync-only"
    }

    $output = & python @args 2>&1
    $output | ForEach-Object { Write-Host $_ }
    if ($LASTEXITCODE -ne 0) {
        throw "Remote deploy command failed."
    }
    return $output
}

function Get-MarkerValue {
    param(
        [object[]]$Lines,
        [string]$Marker
    )
    $line = $Lines | Where-Object { "$_".StartsWith($Marker) } | Select-Object -First 1
    if (-not $line) {
        return ""
    }
    return ("$line").Substring($Marker.Length).Trim()
}

function Invoke-PublicChecks {
    $results = @()
    foreach ($url in $PublicChecks) {
        $code = & curl.exe --noproxy "*" -k -sS -o NUL -w "%{http_code}" $url
        if ($LASTEXITCODE -ne 0) {
            throw "Public check failed: $url"
        }
        $status = "$url -> $code"
        Write-Host $status
        if ("$code" -ne "200") {
            throw "Public check returned $code for $url"
        }
        $results += $status
    }
    return $results
}

function Add-OnlineUpdateLog {
    param(
        [string]$RuntimeCommit,
        [string]$BackupPath,
        [string[]]$PublicResults
    )

    $logPath = Join-Path $Root "ONLINE_UPDATE_LOG.md"
    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    $content = [System.IO.File]::ReadAllText($logPath, $utf8NoBom)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
    $publicText = ($PublicResults -join "; ")
    $entry = @"
## $timestamp Asia/Shanghai

- Scope: $ChangeScope
- Verification: local one-click deploy script completed; $publicText; remote standard deploy completed for runtime commit $RuntimeCommit; health check and service status were printed by the deploy script.
- Deploy: local scripts/deploy/push-and-deploy.ps1 pushed $Remote/$Branch, then ran bash scripts/deploy/production-deploy.sh in $DeployRepoDir on the server.
- Server backup: $BackupPath
- Notes: generated by the one-click deploy script; `/www/wwwroot/quick-translate` was not changed.

"@

    $match = [regex]::Match($content, "(?m)^## \d{4}-\d{2}-\d{2} ")
    if (-not $match.Success) {
        throw "ONLINE_UPDATE_LOG.md does not contain a dated entry insertion point."
    }
    $updated = $content.Insert($match.Index, $entry)
    [System.IO.File]::WriteAllText($logPath, $updated, $utf8NoBom)
}

Push-Location $Root
try {
    Invoke-Step "Preflight" {
        Invoke-Native "python" @("-c", "import paramiko")
        $currentBranch = Get-GitOutput @("branch", "--show-current")
        if ($currentBranch -ne $Branch) {
            throw "Current branch is '$currentBranch', expected '$Branch'."
        }
        $status = Get-GitOutput @("status", "--porcelain", "--untracked-files=no")
        if ($status) {
            throw "Tracked working tree is not clean. Commit or stash tracked changes before one-click deploy."
        }
    }

    if (-not $SkipQualityGate) {
        Invoke-Step "Quality gate" {
            Invoke-Native "powershell" @("-ExecutionPolicy", "Bypass", "-File", "scripts\quality\check.ps1")
        }
    }

    $plainPassword = Get-PlainPassword
    $oldPassword = $env:EXCELCC_DEPLOY_PASSWORD
    $env:EXCELCC_DEPLOY_PASSWORD = $plainPassword
    try {
        Invoke-Step "Push branch" {
            Invoke-Native "git" @("push", $Remote, $Branch)
        }

        $runtimeCommit = Get-GitOutput @("rev-parse", "--short", "HEAD")
        $deployOutput = Invoke-Step "Remote standard deploy" {
            Invoke-RemoteDeploy
        }
        $backupPath = Get-MarkerValue $deployOutput "LATEST_BACKUP:"
        if (-not $backupPath) {
            throw "Deployment output did not include LATEST_BACKUP marker."
        }

        Invoke-Step "Public smoke checks" {
            $publicResults = Invoke-PublicChecks
            if (-not $SkipOnlineLog) {
                Add-OnlineUpdateLog -RuntimeCommit $runtimeCommit -BackupPath $backupPath -PublicResults $publicResults
                Invoke-Native "git" @("add", "ONLINE_UPDATE_LOG.md")
                Invoke-Native "git" @("commit", "-m", "docs: record production deploy $runtimeCommit")
                Invoke-Native "git" @("push", $Remote, $Branch)
                Invoke-RemoteDeploy -SyncOnly | Out-Null
            }
        }

        Write-Host ""
        Write-Host "Deployment channel completed."
        Write-Host "Runtime commit: $runtimeCommit"
        Write-Host "Backup: $backupPath"
    } finally {
        if ($oldPassword) {
            $env:EXCELCC_DEPLOY_PASSWORD = $oldPassword
        } else {
            Remove-Item Env:\EXCELCC_DEPLOY_PASSWORD -ErrorAction SilentlyContinue
        }
        if ($plainPassword) {
            $plainPassword = $null
        }
    }
} finally {
    Pop-Location
}
